<a href="https://colab.research.google.com/github/rohansiddam/Python-Journey/blob/main/011%20-%20Project%20(Claude%20Shannon%20Algorithm%201).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Instructions

#### Goal of the Project

This project is designed for you to practice and solve the activities that are based on the concepts covered in the following lessons:

  1.  Claude Shannon Algorithm I

---

#### Getting Started

Follow the steps described below to solve the project:

1. Click on the link provided below to open the Colab file for this project.
   
   https://colab.research.google.com/drive/1u2YmTposWFn14Dr_KIvpKtYM2xz08OWy
   
2. Create the duplicate copy of the Colab file. Here are the steps to create the duplicate copy:

    - Click on the **File** menu. A new drop-down list will appear.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/0_file_menu.png' width=500>

    - Click on the **Save a copy in Drive** option. A duplicate copy will get created. It will open up in the new tab on your web browser.

      <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/1_create_colab_duplicate_copy.png' width=500>

     - After creating the duplicate copy of the notebook, please rename it in the **YYYY-MM-DD_StudentName_Project11** format.

3. Now, write your code in the prescribed code cells.

---

### Activities

#### Activity 1: 3D NumPy array

Write a program to create a three-dimensional NumPy array which has 4 blocks, 4 rows and 4 columns such that all the initial items are `0`.

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import `numpy` module.

  - **Step 2**: Pass `(4, 4, 4 )` inside the `shape` attribute of the `zeros()` function to create a 3D NumPy array of size (4, 4, 4) whose all the elements are 0. Store the array in a variable `three_d_arr`.

In [ ]:
# Create a 3D NumPy array of size (4, 4, 4) whose all the elements are 0.
# Step 1: Import numpy module.
import numpy as np
# Step 2: Pass '(4, 4, 4 )' inside the 'shape' attribute of the 'zeros()' function
three_d_arr = np.zeros(shape=(4,4,4),dtype = int)

---

#### Activity 2: Accessing elements in a 3D array.

Given a 3D NumPy array of size (2, 2, 2) whose all the elements are 0,

```
three_d_arr = [[[0 0],
               [0 0]],

              [[0 0],
              [0 0]]]
```

write a program to generate a random number between 10 and 50 at (0, 1, 1) position of the `three_d_arr`. If the random number generated is greater than 20 then, update the 1st element (`update_needed` in the below array) as `50`, else, update it as `20`.

```
three_d_arr = [[[0 update_required],
               [0 random_number]],

              [[0 0],
              [0 0]]]
```

Follow the steps given below to achieve the desired result:

  - **Step 1**: Import the `random` module.

  - **Step 2**: Update the `(0, 1, 1)` position of the `three_d_arr` with a random number between `10` and `50` (including both).

  - **Step 3**: Check whether the random number generated is greater than `20` using an `if` condition.

     - If the condition is `True`, update the `0` at `(0, 0, 1)` i.e. `update_required` position with `50`.

     - Else, update it as `20`.

In [ ]:
# 3D NumPy array of size (2, 2, 2) whose all the elements are 0.
import numpy as np

three_d_array = np.zeros(shape=(2, 2, 2), dtype=int)
three_d_array

array([[[0, 0],
        [0, 0]],

       [[0, 0],
        [0, 0]]])

In [ ]:
# Write your code here to generate a random number between 10 and 50 at (0,1,1)
import random as rd
three_d_array[0][1][1] = rd.randint(10,50)

In [ ]:
# Check whether the random number generated is greater than 20
if three_d_array[0][1][1] > 20:
  three_d_array[0][0][1] = 50
else:
  three_d_array[0][0][1] = 20
  # If the condition is 'True', update the '0' at '(0, 0, 1)' position with '50'.

# print the resultant 'three_d_array' array
print(three_d_array)

[[[ 0 50]
  [ 0 22]]

 [[ 0  0]
  [ 0  0]]]


---

### Submitting the Project

Follow the steps described below to submit the project.

1. After finishing the project, click on the **Share** button on the top right corner of the notebook. A new dialog box will appear.

  <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/2_share_button.png' width=500>

2. In the dialog box, click on the **Copy link** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/3_copy_link.png' width=500>


3. The link of the duplicate copy (named as **YYYY-MM-DD_StudentName_Project11**) of the notebook will get copied

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/4_copy_link_confirmation.png' width=500>

4. Go to your dashboard and click on the **My Projects** option.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/5_student_dashboard.png' width=800>

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/6_my_projects.png' width=800>

5. Click on the **View Project** button for the project you want to submit.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/7_view_project.png' width=800>

6. Click on the **Submit Project Here** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/8_submit_project.png' width=800>

7. Paste the link to the project file named as **YYYY-MM-DD_StudentName_Project11** in the URL box and then click on the **Submit** button.

   <img src='https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/project-share-images/9_enter_project_url.png' width=800>


---