<a href="https://colab.research.google.com/github/rohansiddam/Python-Journey/blob/main/011%20-%20Lesson%2011%20(Mind%20Reader%20Game%20-%20Claude%20Shannon's%20Algorithm%201).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 11: Mind Reader Game - Claude Shannon's Algorithm I

### Teacher-Student Activities

The Mind Reader game algorithm is built around the machine invented by Claude Shannon in 1953. He named it "A Mind Reading Machine". It predicts a player's next move based on his/her previous inputs.

You can read about the machine by clicking on the following link provided in the **Activities** section under the title **A Mind Reader Machine - Claude E. Shannon**

**Note:** *The algorithm is quite complicated to understand and to create. For all practical purposes, you just need to know how to apply the algorithm. It is completely all right if you do not understand how to create this algorithm.*

In this algorithm, the computer looks for certain patterns in the player inputs (`Heads` or `Tails`) and tries to remember them. Furthermore, it assumes that the player will follow these patterns the next time if the same situation arises.

The computer also contains an element of randomness. If an assumed pattern is not repeated at least twice by the player, the machine predicts `Heads` or `Tails` randomly.

The types of patterns remembered, involve the outcome of two successive plays, i.e., whether or not the player won on those plays and whether the player changed their choice between the plays and after the plays.

There are 8 possible situations and, for each situation, a player can do two things. These 8 situations are:

1. The player **wins**, plays the **same** and **wins** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Heads` again and wins again. In the next attempt, he/she may play either `Heads` or `Tails`.

2. The player **wins**, plays the **same** and **loses**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Heads` again and loses. In the next attempt, he/she may play either `Heads` or `Tails`.

3. The player **wins**, plays **differently** and **wins** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Tails` and wins again. In the next attempt, he/she may play either `Heads` or `Tails`.

4. The player **wins**, plays **differently** and **loses**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, wins, then plays `Tails` and loses. In the next attempt, he/she may play either `Heads` or `Tails`.

5. The player **loses**, plays the **same** and **wins**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Heads` again and wins. In the next attempt, he/she may play either `Heads` or `Tails`.

6. The player **loses**, plays the **same** and **loses** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Heads` again and loses again. In the next attempt, he/she may play either `Heads` or `Tails`.

7. The player **loses**, plays **differently** and **wins**. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Tails` and wins. In the next attempt, he/she may play either `Heads` or `Tails`.

8. The player **loses**, plays **differently** and **loses** again. The player then plays the same or plays differently.

    - For example, a player plays `Heads`, loses, then plays `Tails` and loses again. In the next attempt, he/she may play either `Heads` or `Tails`.

Each situation corresponds to a different cell in the memory of a machine. Within a cell, two events are registered:

1. Whether the last time this situation arose, the player played the same or different.

2. Whether or not the behaviour indicated in the first point, was a repeat of the same behaviour in the preceding situation.

Consider the situation **win**, **same** and **lose**, i.e., the second situation out of the 8 possible situations.

Suppose that the last time the second situation occurred, the player played **differently**. So **differently** is recorded in the first part of the memory cell. If at the preceding juncture, the second situation arose and the player again played **differently**, the second part of the memory cell registers this as a repeat.

If this situation arises again, the machine will assume that this is a definite pattern in the player's behaviour and will play accordingly. If the player does not repeat, the machine makes prediction randomly. The memory cells are always kept up to date.


Taking inspiration from Claude Shannon's "A Mind Reading Machine", in our algorithm, we will create three-dimensional array having 2 blocks, 2 rows and 2 columns to keep track of the last two player inputs and the current player input.

```
[[[0, 0],
  [0, 0]],

 [[0, 0],
  [0, 0]]]
```

So, for a combination of the last two player inputs and the current player input, if a situation is repeated then we will store `1` in the second column of the array otherwise, we will store `0`.


Here's the implementation of the Cluade Shannon's "A Mind Reading Machine" based algorithm in Python. We will cover half of it in this class and the remaining half in the next class as it is a very complicated and a very lengthy algorithm.

```
import random
import numpy as np

inputs = np.zeros(shape=(2, 2, 2), dtype=int)

last_1 = 0
last_2 = 0

scores = [0, 0] # [computer_score, player_score]

def update_inputs(current):
  global last_1, last_2
  if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1
    inputs[last_2][last_1][0] = current
  else:
    inputs[last_2][last_1][1] = 0
    inputs[last_2][last_1][0] = current
  
  last_1 = current # current becomes last_1
  last_2 = last_1 # last_1 becomes last_2
    
def prediction():
  if inputs[last_2][last_1][1] == 1:
    predict = inputs[last_2][last_1][0]    
  else:
    predict = random.randint(0, 1)  
  return predict

def update_scores(predicted, player_input):  
  if predicted == player_input:
    scores[0] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nYour Score: ", scores[1])
        
  else:
    scores[1] = scores[0] + 1
    print("\nComputer Score:", scores[0], "\nYour Score:", scores[1])

def reset():
  for i in range(2):
    for j in range(2):
      for k in range(2):
        inputs[i][j][k] = 0
  
  for i in range(2):
    scores[i] = 0

def gameplay():
  reset()
  valid_entries = ['0', '1']
  while True:
    player_input = input("\nEnter either 1 or 0: ")
    
    while player_input not in valid_entries:
      print("\nInvalid Input!")
      player_input = input("Please enter either 1 or 0: ")
    
    player_input = int(player_input)  
    predicted = prediction()
    update(player_input)
    update_scores(predicted, player_input)
        
    if scores[0] == 50:
      print("\nBad Luck, Computer Wins!\n")
      break
        
    elif scores[1] == 50:
      print("\nCongrats, You Won!\n")
      break
```

Let's get started.

---

#### Activity 1: Last Two Players Inputs

Let's create two variables: `last_1` and `last_2` to keep a track of the last two inputs of a player. Also, let's set their initial values equal to `0`.

In [ ]:
# Student Action: Create two variables; 'last_1' and 'last_2' with 0 as their initial values.
last_1 = 0
last_2 = 0


- `last_1` stores the last player input.

- `last_2` stores the second-last player input.




---

#### Activity 2: NumPy Array

Now, let's create a three-dimensional NumPy array which has 2 blocks, 2 rows and 2 columns such that all the initial items are `0`. Let's store it in the `inputs` variable.

```
inputs = [[[0 0],
           [0 0]],

          [[0 0],
           [0 0]]]
```

In [ ]:
# Student Action: Create a 3D NumPy array of size (2, 2, 2) whose all the elements are 0.
import numpy as np
inputs = np.zeros((2,2,2),dtype = int)
print(inputs)

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


The `inputs` array acts as a memory for the Mind Reader game.

- The first column (`column_index = 0`) of the `inputs` array will store the current player input.

- The second column (`column_index = 1`) will store whether a situation (out of the 8 possible situations) is repeated or not. The 8 possible situations are:

|Situation|Second-Last Play|Last Play|Current Player Input|
|-|-|-|-|
|1.|`0`|`0`|`0`|
|2.|`0`|`0`|`1`|
|3.|`0`|`1`|`0`|
|4.|`0`|`1`|`1`|
|5.|`1`|`0`|`0`|
|6.|`1`|`0`|`1`|
|7.|`1`|`1`|`0`|
|8.|`1`|`1`|`1`|

where `0` denotes `Heads` and `1` denotes `Tails`.

The blocks in the `inputs` array denote the second-last play.

- If `last_2 = 0`, then the `last_1` value will go to the first/second row of the **first** block.

- If `last_2 = 1`, then the `last_1` value will go to the first/second row of the **second** block.

<img src = 'https://student-datasets-bucket.s3.ap-south-1.amazonaws.com/images/inputs_array.png' width=600>

At a time, the **current player input** will either go to the first block or second block because the second-last play would either be `0` or `1`.

Here are the possible ways in which the current player inputs will be recorded in the first block.

1. All the items in the first column are `0`.

  ```
  [[0, is_a_repeat],
    [0, is_a_repeat]]
  ```

2. The item in the first row and first column is `0` but the item in the second row and the first column is `1`.

  ```
  [[0, is_a_repeat],
    [1, is_a_repeat]]
  ```

3. The item in the first row and first column is `1` but the item in the second row and the first column is `0`.

  ```
  [[1, is_a_repeat],
    [0, is_a_repeat]]
  ```

4. All the items in the first column are `1`.

  ```
  [[1, is_a_repeat],
    [1, is_a_repeat]]
  ```

The value of `is_a_repeat` is either `0` or `1`.

  - The value `0` or `1` in the first column represents whether the player played `Heads` or `Tails`, respectively, in the last attempt.
  
  - The value `0` or `1` in the second column represents whether a situation (a combination of `last_2, last_1` and current player input) is repeated or not. The value `0` means the situation is NOT repeated and `1` means the situation is repeated.

The second block will also have the exact same possibilities.

---

#### Activity 3: The `update_inputs()` Function
Now, we are going to update the entries of the `inputs` array by creating a function. Let's name this function as `update_inputs()`. It should take `current` player input as an input and should not return anything. It should just update the player inputs in the `inputs` array.

For a row in a block, if an item in the $1^{st}$ column is the same as the `current` player input, then set the value in the $2^{nd}$ column equal to `1`, and set the value in the $1^{st}$ column equal to the `current` player input.

```
if inputs[last_2][last_1][0] == current:
    inputs[last_2][last_1][1] = 1
    inputs[last_2][last_1][0] = current
```

Otherwise, set the value in the $2^{nd}$ column equal to `0` and set the value in the $1^{st}$ column equal to the `current` value.

```
inputs[last_2][last_1][1] = 0
    inputs[last_2][last_1][0] = current
```

Then, the `current` value should become the `last_1` value and the `last_1` value should become the `last_2` value.

```
  last_2 = last_1
  last_1 = current
```

In [ ]:
# Teacher Action: Create the 'update_inputs()' function.
def update_inputs(current_input):
  global last_1,last_2
  if inputs[last_2][last_1][0] == current_input:
    inputs[last_2][last_1][1] = 1
    inputs[last_2][last_1][0] = current_input

  else:
    inputs[last_2][last_1][1] = 0
    inputs[last_2][last_1][0] = current_input

  last_2 = last_1
  last_1 = current_input


---

#### Activity 4: The `prediction()` Function^

Now, let's create a function and name it `prediction()`. This function will allow a computer to make predictions based on the player inputs in the last two plays.

For a row in a block, if the value in the $2^{nd}$ column is `1`, then the `prediction()` function should return the item stored in the $1^{st}$ column as the predicted value.

```
if inputs[last_2][last_1][1] == 1:
    predict = inputs[last_2][last_1][0]
```

Else, either return `0` or `1` randomly as the predicted value.

```
else:
    predict = random.randint(0, 1)
```

Essentially, if the item in the second column is `1`, then return the item stored in the first column as the predicted value. Else, predict `0` or `1` randomly.

In [ ]:
# Teacher Action: Create the 'prediction()' function which returns the predicted value.
import random as rd
def prediction():
  if inputs[last_2][last_1][1] == 1:
    predict = inputs[last_2][last_1][0]
    print("I am inside the if function")
  else:
    predict = rd.randint(0,1)
    print("I am inside the else function")
  return predict

In [ ]:
print(last_1)
print(last_2)
print(inputs)

0
0
[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [ ]:
user_input = int(input("Enter either 0 or 1: "))
update_inputs(user_input)
print(last_1)
print(last_2)
print(inputs)

Enter either 0 or 11
1
0
[[[1 0]
  [0 0]]

 [[0 0]
  [0 0]]]


In [ ]:
user_input = int(input("Enter either 0 or 1: "))
update_inputs(user_input)
print(last_1)
print(last_2)
print(inputs)

Enter either 0 or 1: 1
1
1
[[[1 0]
  [1 0]]

 [[0 0]
  [0 0]]]


In [ ]:
user_input = int(input("Enter either 0 or 1: "))
update_inputs(user_input)
print(last_1)
print(last_2)
print(inputs)

Enter either 0 or 1: 1
1
1
[[[1 0]
  [1 0]]

 [[0 0]
  [1 0]]]


In [ ]:
user_input = int(input("Enter either 0 or 1: "))
update_inputs(user_input)
print(last_1)
print(last_2)
print(inputs)

Enter either 0 or 1: 1
1
1
[[[1 0]
  [1 0]]

 [[0 0]
  [1 1]]]


In [ ]:
prediction()

I am inside the if function


1

In [ ]:
user_input = int(input("Enter either 0 or 1: "))
update_inputs(user_input)
print(last_1)
print(last_2)
print(inputs)

Enter either 0 or 1: 1
1
1
[[[1 0]
  [1 0]]

 [[0 0]
  [1 1]]]


In [ ]:
prediction()

I am inside the if function


1

In [ ]:
user_input = int(input("Enter either 0 or 1: "))
update_inputs(user_input)
print(last_1)
print(last_2)
print(inputs)

Enter either 0 or 1: 0
0
1
[[[1 0]
  [1 0]]

 [[0 0]
  [0 0]]]


In [ ]:
prediction()

I am inside the else function


1

All right! We will stop here now. In the next class, we will create the following functions to complete the algorithm:

1. The `update_scores()` function

2. The `reset()` function

3. The `gameplay()` function

Create a function that asks a user for a positive integer and then prints out a list containing all of its the divisors.

**What is a divisor?**

It is a number that divides into another without leaving a remainder. E.g., 3 is a divisor of 27 because 27 divided by 3 leaves no remainder.

In [ ]:
user_input = int(input("Enter a positive integer: "))
def divisor(user_input):
  divisor_list = []
  i = 1
  while i <= user_input:
    if (user_input % i) == 0:
      divisor_list.append(i)
    i+= 1

  return divisor_list

print(divisor(user_input))

Enter a positive integer: 27
[1, 3, 9, 27]


---


### **Project**

You can now attempt the **Project 11 - Claude Shannon Algorithm I** on your own.


**Project 11 - Claude Shannon Algorithm I**: https://colab.research.google.com/drive/1u2YmTposWFn14Dr_KIvpKtYM2xz08OWy

---