<a href="https://colab.research.google.com/github/rohansiddam/Python-Journey/blob/main/Copy_of_2022_19_6_ROHAN_Lesson_9_Class_Copy_v0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lesson 9: NumPy Arrays I


### Teacher-Student Activities

In the previous lesson, we learnt how to create a Python list using the list comprehension method. In this lesson, we are going to learn how to create NumPy arrays.

An array is also a data-structure which contains multiple values. Working with NumPy arrays is much easier than working with Python lists.

The term NumPy stands for Numeric (or Numerical) Python. It is one of the most popular modules amongst Statisticians and Data Scientists across the globe to perform heavy mathematical computations. NumPy arrays are also faster than Python lists in terms of code execution time.

For all practical purposes, **an array is the same as a list**. Fundamentally, they have been programmed differently by the inventors of Python language. We are **NOT** required to know how they were created. We only need to know how to apply them in different situations.


---

#### Activity 1: NumPy Arrays - The `ones()` & `zeros()` Functions

To get started with NumPy arrays, let's create an array having each item as `1` with dimensions `5` blocks, `3` rows and `3` columns.

To create such an array, you first need to `import` the `numpy` module at the beginning of the code. Then use the `ones()` function from the `numpy` module.

The `ones()` function requires two inputs. The first input should be the required dimension of the array and the second input should define the data-type of the items in the required array.


In [ ]:
# Teacher Action: Create an array containing '1' as its items using the 'ones()' function from the 'numpy' module.
import numpy as np
onesArray = np.ones((5,3,3),dtype = int)
onesArray
# Step 1: Always import the 'numpy' module at the beginning of the code and give it an alias (or nickname) called np.
# We will always refer to the 'numpy' module as 'np' throughout the code.

# Step 2: Call 'ones()' function from the np module using the dot operator.
# The 'ones()' function, requires two inputs: the dimension of the array and data-type of the items which in this case is 'int'.


array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

**Note:**

1. Always import the `numpy` module at the beginning of the code with `np` as its alias (or nickname). Throughout the course, we will always refer to the `numpy` module as `np` unless otherwise specified.

2. The de facto data-type of an item in a NumPy array is `float`.

Using the `type()` function, you can verify whether an array is a NumPy array or not.

In [ ]:
# Teacher Action: Using the 'type()' function, verify whether the 'ones' array is a NumPy array or not.
type(onesArray)

numpy.ndarray

As you can see, the `type()` function has returned `numpy.ndarray` as an output which confirms that the `ones` array is indeed a NumPy array.

Similarly, you try to create a NumPy array having each item as `0` with dimensions `4` blocks, `2` rows and `3` columns using the `zeros()` function. Make sure that each item is an integer.


In [ ]:
# Student Action: Using 'zeros()' function, create a NumPy array having 4 blocks, 2 rows and 3 columns. The items should be int data-type.
zerosArray = np.zeros((4,2,3),dtype = int)
print(zerosArray)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]


Recreate the above array without providing the data-type as input. The output should be a three-dimensional array with each item as `0.` which is a floating-point number.

Here's the desired output:

```
array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])
```

In [ ]:
# Student Action: Using 'zeros()' function, create a numpy array having 4 blocks, 2 rows and 3 columns.
zArray = np.zeros((4,2,3))
print(zArray)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


As you can see, all the items of the `zero_float` array are of `float` data-type.


---

#### Activity 2: The `dtype` Keyword

To check the data-type of the values stored in a NumPy array, you can use the `dtype` keyword.


In [ ]:
# Student Action: Using the 'dtype' keyword, verify whether the 'zeros_float' array items are floating-point values or not.
zArray.dtype

dtype('float64')

For the time being ignore the number `64`. As you can see, the `dtype` keyword has returned `dtype('float64')` as an output confirming that all the items of the `zeros_float` array are floating-point values.


In [ ]:
# Student Action: Using the 'dtype' keyword, verify whether the 'ones' array items are int values or not.
onesArray.dtype

dtype('int64')

For the time being ignore the number `64`. As you can see, the `dtype` keyword has returned `dtype('int64')` as an output confirming that all the items of the `ones` array are integer values.


**Difference Between The `type()` Function & The `dtype` Keyword**

The `type()` function is a function of Python. It returns the type of Python object. The data-types or more accurately the **primitive data-types** `int`, `float`, `str` and `bool` are actually Python objects. Similarly, Python lists, NumPy module, `random` modules are also Python objects. The `type()` function will tell you what type of Python objects they are.

In [ ]:
# Student Action: Run the code shown below to see that the 'type()' function returns the type of Python object.
import random as rd
# 1. The 'int' Python object.
print(type(6))
# 2. The 'float' Python object.
print(type(6.5))
# 3. The 'str' Python object.
print(type("Hello"))
# 4. The 'list' Python object
print(type([1,2,3,4]))
# 5. 'numpy' is a 'module' Python object.
print(type(np))
# 6. 'random' is a 'module' Python object.
print(type(rd))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'list'>
<class 'module'>
<class 'module'>


In the output, ignore the term `class`. As you can see, the `type()` function indeed returns the type of Python object for an entity in Python.

---

#### Activity 3: The `ndim` And `shape` Keywords

**The `ndim` Keyword:** Using the `ndim` keyword, you can find out the dimension of a NumPy array. The `ones`, `zeros` and `zeros_float` arrays are three-dimensional arrays. So, the `ndim` keyword should return `3` for each of these arrays.

In [ ]:
# Student Action: Using the 'ndim' array, find out the dimension of 'ones', 'zeros' and 'zeros_float' NumPy arrays.
onesArray.ndim

3

**The `shape` Keyword:** Using the `shape` keyword, you can find out the number of blocks, rows and columns present in NumPy arrays.

In [ ]:
# Student Action: Using the 'shape' keyword find out the number of blocks, rows and columns in the 'ones', 'zeros' and 'zeros_float' arrays.
onesArray.shape

(5, 3, 3)

As you can see:

- The `ones` array has 5 blocks, 3 rows and 3 columns.

- The `zeros` array has 4 blocks, 2 rows and 3 columns.

- The `zeros_ones` array also has 4 blocks, 2 rows and 3 columns.

---

#### Activity 4: The `arange()` And `linspace()` Functions^^

The are `arange()` and `linspace()` functions in NumPy module create an array of numbers such that the difference between a pair of any two consecutive numbers in the array is constant. However, there is a slight difference in their outputs.

**The `arange()` Function:** It returns a one-dimensional array containing numbers between two specific numbers. It is similar to the `range()` function in the `for` loop.

In [ ]:
# Student Action: Create a one-dimensional array containing numbers between 5 and 20 using the 'arange()' function in the NumPy module.
array1 = np.arange(5,21)
print(array1)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Here, the `arange()` function has created an array of numbers from `5` to `20`. The difference between a pair of any two consecutive numbers is `1`. The `arange()` function will not include the last number specified in the array created.

If you want the difference between two consecutive numbers to be greater than `1` (say `4`) in an array, then you can specify the difference as an additional input to the `arange()` function.

In [ ]:
# Student Action: Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4.
array2 = np.arange(1,25,4)
print(array2)

[ 1  5  9 13 17 21]


As you can see, the `arange()` function has created an array of numbers from `1` to `24` such that the difference between two consecutive numbers is `4`.

**Note:** If the difference between two consecutive numbers is not specified, then the `arange()` function will assume that the difference is `1`.

You can also create an array containing the floating-point numbers using the `arange()` function by providing `dtype=float` as an additional input to the function.

In [ ]:
# Student Action: Create an array of numbers from 1 to 24 such that the difference between two consecutive numbers is 4 and each item is a float.
array3 = np.arange(1,25,4,dtype = float)
print(array3)

[ 1.  5.  9. 13. 17. 21.]


As you can see, the items contained in `array3` are floating-point numbers.

**The `linspace()` Function:** This function creates an array containing a fixed number of numbers between two specific numbers such that the difference between any two consecutive numbers in the array is constant. This will be clear to you with an example.

Suppose you want to create an array containing exactly `4` numbers between the numbers `1` and `25` such that all the difference between any two consecutive numbers is constant, then you can use the `linspace()` function.

In [ ]:
# Student Action: Create an array containing 4 numbers between 1 to 25.
array4 = np.linspace(1,25,4)
print(array4)

[ 1.  9. 17. 25.]


As you can see, the `linspace()` function has created an array containing `4` numbers between `1` and `25` (including `25`) such that the difference between two consecutive numbers is constant. Take a pair of any two consecutive numbers in `array5`, the difference between them will be `8.`

Notice the difference between the outputs of the `arange()` and `linspace()` functions for exactly the same inputs. The `arange()` function returns `6` numbers such that the difference between them is exactly `4` whereas the `linspace()` function returns exactly `4` numbers such that the difference between two consecutive numbers is constant.

In other words:

- In the `arange()` function, you specify the value of the difference between two consecutive numbers as the third input.

- Whereas, in the `linspace()` function, you specify the length of the array to be created as the third input.

Let's create another array using the `linspace()` function to get a better understanding. Let's create an array containing `10` numbers between `1` and `25` such that the difference between two consecutive numbers is constant.


In [ ]:
# Student Action: Create an array containing 10 numbers between 1 and 25 such that the difference between two consecutive numbers is constant.
array5 = np.linspace(1,25,10)
print(array5)

[ 1.          3.66666667  6.33333333  9.         11.66666667 14.33333333
 17.         19.66666667 22.33333333 25.        ]


Take a pair of any two consecutive numbers in the `array5`, the difference between them will be `2.66666666`

---

#### Activity 5: The `reshape()` Function


The `reshape()` function reshapes an array from one configuration to another without changing the items.

The `zeros` array has 4 blocks, 2 rows and 3 columns. Suppose you want to reshape it into another array having `6` rows and `4` columns without changing the items, then you can use the `reshape()` function.

In [ ]:
# Student Action: Reshape the 'zeros' array so that it has 6 rows and 4 columns.
# Before reshaping
print(zerosArray)
print(zerosArray.shape)
# After reshaping
reshapeZerosArray = zerosArray.reshape(6,4)
print(reshapeZerosArray)

[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(4, 2, 3)
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


The `reshape()` function has reshaped the `zeros` array to a two-dimensional array having 6 rows and 4 columns. Inside the `reshape()` function, you have to provide the new configuration.

This operation is only valid when the number of items in the new configuration is exactly the same as the number of items in the original configuration.

In this case, there are 24 items (4 blocks $\times$ 2 rows $\times$ $3$ columns = 24 items) in the original configuration. So the new configuration must also have 24 items.

You can also convert a multi-dimensional array into a one-dimensional array using the `reshape()` function. Let's convert `ones` into a one-dimensional array using the `reshape()` function. It has 45 items. The reshaped array must also contain 45 items.

In [ ]:
# Student Action: Reshape the 'ones' array so that it has just 1 row.
reshapeOnesArray = onesArray.reshape(45)
print(reshapeOnesArray)
print(onesArray.shape)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1]
(5, 3, 3)


As you can see, the three-dimensional array is converted into a one-dimensional array using the `reshape()` function.

---

#### Activity 6: The `ndarray()` Function
In general, we can create a NumPy array containing some random values using `ndarray()` function.

Let's say we want to create a NumPy array having some random integer values which have 5 rows and 2 columns, then you can use the `ndarray()` function.

Similar to the `zeros()` and `ones()` functions, the `ndarray()` function takes two inputs: the first input is the configuration of the required array and the second input is the data-type of items. The de facto data-type is a floating-point value.

In [ ]:
# Student Action: Create a 'numpy' array using 'ndarray()' function having 5 rows and 2 columns.
array6 = np.ndarray((5,2),dtype = int)
print(array6)

[[4607182418800017408 4615439018116863317]
 [4618816717837391189 4621256167635550208]
 [4622757367511340373 4624258567387130538]
 [4625478292286210048 4626228892224105130]
 [4626979492162000213 4627730092099895296]]


---

#### Activity 7: The `random.randint()` Function

The NumPy module also has its `random.randint()` function. It takes two inputs. The first input is the range of two integers between which a random number is to be created. The second input is the `size` parameter which defines the number of random integers to be created.

**Syntax:** `np.random.randint(num1, num2, size=N)`

 where `num1` and `num2` are starting numbers and `N` is the number of items to be contained in the array.

In [ ]:
# Student Action: Create a one-dimensional NumPy array containing 15 random integers between 50 and 100.
randArray = np.random.randint(50,100,size = 15)
print(randArray)

[80 68 80 63 72 92 88 79 84 89 57 86 69 50 53]


Similarly, you can create a multi-dimensional NumPy array containing random integers by specifying the dimensions of the array to be created in the `size` parameter.

In [ ]:
# Student Action: Create a two-dimensional NumPy array containing 15 random integers between 50 and 100.
randArray2 = np.random.randint(50,100,size = (5,3))
print(randArray2)

[[70 51 85]
 [63 74 62]
 [56 95 88]
 [61 60 62]
 [61 99 72]]


In [ ]:
# Student Action: Create a three-dimensional NumPy array containing 40 random integers between 50 and 100.
randArray3 = np.random.randint(50,100,size = (2,10,2))
print(randArray3)

[[[69 71]
  [86 70]
  [58 57]
  [65 61]
  [85 63]
  [50 70]
  [53 68]
  [78 68]
  [81 98]
  [66 59]]

 [[59 50]
  [50 67]
  [68 71]
  [64 60]
  [50 58]
  [64 56]
  [96 82]
  [50 79]
  [62 53]
  [72 79]]]


---

#### Activity 8: The `array()` Function^

We can convert a Python list into a NumPy array. To do this, use the `array()` function which takes a Python list as an input.

Let's first create a list of natural numbers from `1` to `15` using the list comprehension method. Then convert the list into a NumPy array using the `array()` function.

In [ ]:
# Student Action: Convert a Python list into a NumPy array using the 'array()' function.
list1 = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
listArray = np.array(list1)
print(listArray)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
<class 'list'>
<class 'numpy.ndarray'>


To check whether a Python list is converted into a NumPy array or not, you can use the `type()` function.

In [ ]:
# Student Action: Verify whether the 'arr' array is a NumPy array or a Python list.
print(type(list1))
print(type(listArray))

<class 'list'>
<class 'numpy.ndarray'>


---

#### Activity 9: The `list()` Function

We can convert a NumPy array into a Python list using the `list()` function.

Let's convert the `arr` NumPy array into a Python list using the `list()` function.

In [ ]:
# Student Action: Convert a NumPy array into a Python list using the 'list()' function.
arrayList = list(listArray)
print(arrayList)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Let's verify whether the conversion happened or not using the `type()` function.

In [ ]:
# Student Action: Verify whether the 'arr_converted' list is Python list or not.
print(type(arrayList))

<class 'list'>


In [ ]:
3**2

9

In [ ]:
round(np.sqrt(64))

8

As you can see, the output is `list`. Hence, we successfully converted the NumPy array to a Python list using the `list()` function.

---

#### Activity 10: The `sqrt()` Function^^^

One of the most notorious concepts in maths is Heron's formula. It calculates the area of a triangle having sides $a, b \space \text{and} \space c$.

<img src='https://drive.google.com/uc?id=18SFm-ovV_QnKufMNNaXB6aWhIhT1cVki' width=500>

According to the Heron's formula, the area of a triangle is given by

$$\text{Area} = \sqrt{s(s-a)(s-b)(s-c)}$$

where

$$s = \frac{a + b + c}{2}$$

i.e., the semi-perimeter of a triangle.

Let's create a function which takes the lengths of the sides of a triangle and checks whether the lengths indeed represent the lengths of the sides of a triangle.

*The sum of lengths of any two sides of a triangle is always greater than the length of the third side.*

If the lengths meet the criteria for being the lengths of the sides of a triangle, then the function should return `True`. Else it should return `False`.

In [ ]:
# Student Action: Create a function to check whether the input lenghts represent the lengths of the side of a triangle.
def is_triangle(a,b,c):
  if ((a + b) > c) and ((b + c) > a) and ((c + a) > b):
    return True
  else :
    return False

Now, let's create a function to calculate the area of a triangle using the Heron's formula. The function must include the `is_triangle()` function and `np.sqrt()` functions. If the invalid side lengths are passed as input to the function, then it should return `Invalid triangle.` message else it should return the area of a triangle.


In [ ]:
# Student Action: Create a function to calculate the area of a triangle using the Heron's formula.
def area_triangle(num1, num2, num3) :
  if is_triangle(num1,num2,num3) == True:
    s = (num1 + num2 + num3) / 2
    return np.sqrt(s * (s-num1) * (s-num2) * (s - num3))
  else :
    return ("Invalid Triangle")

In [ ]:
print(area_triangle(5,1,7))

Invalid Triangle


Alternatively, you can raise a number to the power `0.5` to calculate the square root of a number, but it will return a complex number as an output for a negative number. On the other hand, the `np.sqrt()` function returns `nan` for negative numbers. It stands for **not a number** and denotes a NumPy null value.

---


### **Project**

You can now attempt the **Applied Tech. Project 9 - Numpy Arrays I** on your own.


**Applied Tech. Project 9 - Numpy Arrays I**: https://colab.research.google.com/drive/1ILR--dEixHlEbutCOYeerv_DdRAGPnZl

---